#!/usr/bin/env bash

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master"  ]; then
      echo "You can't commit directly to master branch"
      exit 1
fi

if $(awk -F"[<>]" '/EMAIL/ {getline;print $3}' workflow/info.plist | grep -q @); then
    echo "You can't commit an email address in the workflow/info.plist (Workflow config)."
    exit 1
fi
